"""modify podcast participants column

Revision ID: 577a9f898681
Revises: b710d30d1e63
Create Date: 2021-03-06 13:26:42.461844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577a9f898681'
down_revision = 'b710d30d1e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('participants', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'participants')
    # ### end Alembic commands ###
